"""Property-based tests over randomly generated valid DAGs.

The example-based tests check graphs someone thought of. These check graphs
nobody thought of, which is where scheduler bugs live — a diamond nested inside
a fan-in inside a chain, with a step that has six dependencies and one that has
none.

DAGs are generated by only ever drawing edges from a lower index to a higher
one. That makes them acyclic by construction, so the generator never wastes
draws on invalid graphs and every example actually exercises the scheduler
rather than the validator.
"""

from __future__ import annotations

import asyncio
from typing import Any

from hypothesis import HealthCheck, given, settings as hypothesis_settings, strategies as st

from skein.limits.concurrency import LimitScope, LimitSet
from skein.model.validation import validate_workflow
from skein.runtime.scheduler import Scheduler
from skein.trace.events import StepStatus
from tests.conftest import make_step, make_workflow


@st.composite
def dags(draw: st.DrawFn, max_nodes: int = 10) -> list[tuple[str, list[str]]]:
    """A random DAG as ``[(step_id, dependencies)]``."""
    count = draw(st.integers(min_value=1, max_value=max_nodes))
    nodes: list[tuple[str, list[str]]] = []
    for index in range(count):
        candidates = [f"s{earlier}" for earlier in range(index)]
        dependencies = draw(
            st.lists(
                st.sampled_from(candidates) if candidates else st.nothing(),
                max_size=min(3, len(candidates)),
                unique=True,
            )
        )
        nodes.append((f"s{index}", dependencies))
    return nodes


class OrderTracker:
    def __init__(self) -> None:
        self.finished: set[str] = set()
        self.violations: list[str] = []
        self.current = 0
        self.peak = 0
        self.executions: dict[str, int] = {}

    def tool(self, dependencies: dict[str, list[str]]):
        async def run(**kwargs: Any) -> dict[str, Any]:
            step_id = str(kwargs["step_id"])
            self.executions[step_id] = self.executions.get(step_id, 0) + 1

            # Checked at the moment the step starts, which is the only moment
            # the property can be violated.
            missing = [
                dependency
                for dependency in dependencies[step_id]
                if dependency not in self.finished
            ]
            if missing:
                self.violations.append(f"{step_id} started before {missing}")

            self.current += 1
            self.peak = max(self.peak, self.current)
            try:
                await asyncio.sleep(0)
                return {"step_id": step_id}
            finally:
                self.current -= 1
                self.finished.add(step_id)

        return run


@hypothesis_settings(
    max_examples=40,
    deadline=None,
    # The event loop and registry fixtures are recreated per test, not per
    # example; Hypothesis rightly warns about that, and it is safe here because
    # each example builds its own tracker and workflow.
    suppress_health_check=[HealthCheck.function_scoped_fixture],
)
@given(nodes=dags(), limit=st.integers(min_value=1, max_value=6))
async def test_dependency_order_and_concurrency_hold_for_any_dag(
    nodes: list[tuple[str, list[str]]], limit: int, registry, build_context
) -> None:
    dependencies = {step_id: deps for step_id, deps in nodes}
    tracker = OrderTracker()
    registry.tools.clear()
    registry.register("tracked", tracker.tool(dependencies))

    steps = [
        make_step(step_id, tool="tracked", depends_on=deps, inputs={"step_id": step_id})
        for step_id, deps in nodes
    ]
    workflow = make_workflow(steps, max_concurrency=limit)

    # Every generated graph must also pass validation; a generator that produced
    # invalid workflows would silently stop testing the scheduler.
    validate_workflow(workflow)

    limits = LimitSet(global_limit=limit, default_tool_limit=limit)
    context, state, _ = build_context(workflow, limits=limits)
    await Scheduler(context, limits).run(state)

    assert tracker.violations == []
    assert tracker.peak <= limit
    assert limits.observer.peak(LimitScope.GLOBAL) <= limit
    # No step executed twice.
    assert all(count == 1 for count in tracker.executions.values())
    # Everything settled.
    assert all(step.status is StepStatus.SUCCEEDED for step in state.steps.values())


@hypothesis_settings(
    max_examples=25,
    deadline=None,
    suppress_health_check=[HealthCheck.function_scoped_fixture],
)
@given(nodes=dags(max_nodes=8))
async def test_every_generated_dag_reaches_a_terminal_state(
    nodes: list[tuple[str, list[str]]], registry, build_context
) -> None:
    """No graph shape leaves the scheduler spinning or hanging."""
    dependencies = {step_id: deps for step_id, deps in nodes}
    tracker = OrderTracker()
    registry.tools.clear()
    registry.register("tracked", tracker.tool(dependencies))

    steps = [
        make_step(step_id, tool="tracked", depends_on=deps, inputs={"step_id": step_id})
        for step_id, deps in nodes
    ]
    workflow = make_workflow(steps, max_concurrency=3)
    limits = LimitSet(global_limit=3, default_tool_limit=3)
    context, state, _ = build_context(workflow, limits=limits)

    async with asyncio.timeout(10.0):
        await Scheduler(context, limits).run(state)

    assert state.all_terminal()


@hypothesis_settings(
    max_examples=25,
    deadline=None,
    suppress_health_check=[HealthCheck.function_scoped_fixture],
)
@given(nodes=dags(max_nodes=8), failing_index=st.integers(min_value=0, max_value=7))
async def test_a_failure_anywhere_still_settles_every_step(
    nodes: list[tuple[str, list[str]]], failing_index: int, registry, build_context
) -> None:
    """Whichever step fails, the run terminates and nothing is left pending."""
    dependencies = {step_id: deps for step_id, deps in nodes}
    failing = f"s{failing_index % len(nodes)}"

    async def maybe_fail(**kwargs: Any) -> dict[str, Any]:
        await asyncio.sleep(0)
        if kwargs["step_id"] == failing:
            raise RuntimeError("injected")
        return {"ok": True}

    registry.tools.clear()
    registry.register("tracked", maybe_fail)

    steps = [
        make_step(step_id, tool="tracked", depends_on=deps, inputs={"step_id": step_id})
        for step_id, deps in nodes
    ]
    workflow = make_workflow(steps, max_concurrency=3)
    limits = LimitSet(global_limit=3, default_tool_limit=3)
    context, state, _ = build_context(workflow, limits=limits)

    async with asyncio.timeout(10.0):
        await Scheduler(context, limits).run(state)

    assert state.all_terminal()
    assert state.step(failing).status is StepStatus.FAILED
    # And no permits were stranded.
    assert limits.observer.current(LimitScope.GLOBAL) == 0
